# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [23]:
#code here
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr=arr.reshape(3,4)

arr1=np.ones_like(arr)

arr2=np.vstack((arr,arr1))
arr3=np.hstack((arr,arr1))

print(arr,"\n")
print(arr1,"\n")
print(arr2,"\n")
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]
 [ 1  1  1  1]
 [ 1  1  1  1]] 

[[ 1  2  3  4  1  1  1  1]
 [ 5  6  7  8  1  1  1  1]
 [ 9 10 11 12  1  1  1  1]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [26]:
#code here
def classify_emails(List):
    important_word = ["urgent", "important"]
    promotion_word = ["sale", "deal"]
    spam_word = ["free"]
    
    important_emails = []
    promotions_emails = []
    spam_emails = []
    
    for i in List:
        email_lower = i.lower() 

        for word in important_word:
            if word in email_lower:
                important_emails.append(i)
                break

        for word in promotion_word:
            if word in email_lower:
                promotions_emails.append(i)
                break

        for word in spam_word:
            if word in email_lower:
                spam_emails.append(i)
                break        
    
    return important_emails, promotions_emails, spam_emails


List = [
    "important announcement",
    "check out our latest deal",
    "you won a free nissan GTR (Kash...)"
]

important, promotions, spam = classify_emails(List)

print(important)
print(promotions)
print(spam)

['important announcement']
['check out our latest deal']
['you won a free nissan GTR (Kash...)']


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [30]:
#code here
dictionary = {
    "hello": "hola",
    "thank you": "gracias",
    "sorry": "lo siento",
    "yes": "sí",
    "no": "no"
}

while True:
    word = input("Enter a word or type 'exit' to quit: ").lower()
    
    if word == "exit":
        break

    if word in dictionary:
        print(word, "in Spanish is", dictionary[word])
    else:
        print("Sorry, the translation is not available.")

sorry in Spanish is lo siento
sorry in Spanish is lo siento
hello in Spanish is hola


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [41]:
import pandas as pd
url = "https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"
data = pd.read_csv(url)

global_sales = data.Global_Sales.sum()
print("sales for all games", global_sales,"\n")

highest_sales = data.loc[data.Global_Sales.idxmax()]
print("Game with the highest global sales",highest_sales,"\n")

average_sales = data[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print("Average sales for every region")
print(average_sales)

top_5 = data.groupby('Genre')['Global_Sales'].sum().nlargest(5)
print("Top 5 most popular game ")
print(top_5)
print("\n")

sales_by_region = data.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
most_popular_genre = sales_by_region.NA_Sales.idxmax()
print("Most popular genre in NA", most_popular_genre,"\n")

print(data.tail(10))

top_3 = data.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print("Top 3 gaming platforms")
print(top_3)
print("\n")

market_share = (data.groupby('Genre')['Global_Sales'].sum() / global_sales) * 100
print("Market share for every genre")
print(market_share)
print("\n")

corr_coefficient = data['NA_Sales'].corr(data['EU_Sales'])
print(corr_coefficient)


sales for all games 8920.44 

Game with the highest global sales Rank                     1
Name            Wii Sports
Platform               Wii
Year                2006.0
Genre               Sports
Publisher         Nintendo
NA_Sales             41.49
EU_Sales             29.02
JP_Sales              3.77
Other_Sales           8.46
Global_Sales         82.74
Name: 0, dtype: object 

Average sales for every region
NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64
Top 5 most popular game 
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


Most popular genre in NA Action 

        Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu D

Some tree example

In [3]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [2]:
# pip install networkx


In [1]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))
